---

  - name: Install Docker
    become: true
    pacman:
      name:
        - docker
        - docker-compose
      state: latest

  - name: Add Docker to Systemd
    become: true
    systemd:
      enabled: yes
      state: started
      name: docker
