---

- name: Install Intel Graphics Drivers
  pacman:
    name:
      - xf86-video-intel
      - mesa
        #when: model in ["T460s", "X260"]

- name: Install nvidia Graphics Drivers
  pacman:
    name:
      - xf86-video-nouveau
      - mesa

- name: Install Xorg base
  pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xrdb

- name: Install optional xorg tools
  pacman:
    name:
      - xorg-xmodmap
      - xorg-xrandr
      - xorg-xev
      - xorg-xset
      - xorg-xinput
        #when: not minimal

- name: Set up Xorg for ThinkPad
  pacman:
    name:
      - xf86-input-synaptics
        #when: model in ["T460s", "X260"]


- name: Install LightDM
  pacman:
    name:
      - lightdm
      - lightdm-gtk-greeter
      - lightdm-webkit2-greeter

- name: Configure LightDM
  become: true
  copy: src=files/lightdm.conf dest=/etc/lightdm/lightdm.conf

- name: Enable LightDM in Systemd
  systemd:
    enabled: no
    name: lightdm

- name: Start LightDM in Systemd
  systemd:
    state: stopped
    name: lightdm
