---

- name: Update Pacman and Packages
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install packages
  pacman:
    name:
      - chromium
      - discord
      - firefox
      - git
      - man-db
      - neofetch
      - tmux
      - tree
      - vi
      - vim
      - wget
      - yamllint
      - zsh
    state: latest


- name: Install xfce4
  pacman:
    name:
      - xfce4
      - xfce4-goodies

- name: Install i3-wm
  pacman:
    name:
      - i3-gaps
      - dmenu
      - termite
