---

- name: Install packages
  become: true
  pacman:
    name:
      - vi
      - vim
      - tmux
      - git
      - tree
      - zsh
      - yamllint
      - chromium
      - man-db
      - discord
      - neofetch
      - firefox
    state: latest

